### ISSUE TITLE
unable to build on Mac

### ISSUE THREAD

**Issue by gilesheron** [mengelbart/gst-go#1] opened 2022-11-01 14:09 UTC
when building the feat/simplify-cgo-api branch (as required for rtp-over-quic) I get:

# github.com/mengelbart/gst-go/gstreamer
gst.c:97:22: error: implicit declaration of function 'g_memdup2' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
gst.c:97:22: note: did you mean 'g_memdup'?
/Library/Frameworks/GStreamer.framework/Versions/1.0/include/glib-2.0/glib/gstrfuncs.h:257:23: note: 'g_memdup' declared here
gst.c:97:18: warning: incompatible integer to pointer conversion initializing 'gpointer' (aka 'void *') with an expression of type 'int' [-Wint-conversion]

if I change line 97 to use g_memdup it seems to work ok. 

I suspect the issue is that the Mac version of GStreamer is pulling in an older version of glib that doesn't have g_memdup2

**Comment by mengelbart** [comment] 2022-11-01 20:35
I think you're right, the issue is the glib version. How did you install Gstreamer on mac? With Homebrew, which uses glib 2.74 as a dependency for Gstreamer, I get a deprecation warning for `g_memdup` but building works. But I still run into runtime issues, because Gstreamer can't find some plugins and I suspect that is because Homebrew installs Gstreamer 1.20.4, but gst-plugins-* 1.20.3.

**Comment by gilesheron** [comment] 2022-11-01 20:41
I installed Gstreamer direct from the Gstreamer site rather than from Homebrew...

**Comment by mengelbart** [comment] 2022-11-01 23:14
Ok, I'll try that tomorrow. If the deprecation warning is the only problem we can also just update this to use `g_memdup` to make it work.

**Comment by mengelbart** [comment] 2022-11-01 23:24
I pushed an update with a fix now. 

I also merged another branch with a lot of refactoring. The latest version of rtp-over-quic was already using that branch, anyway. I tagged the previous version as v0.0.1 and the new one as v0.0.2. So in case you were using it, you can still reference the tags.

**Closed as completed by mengelbart** 2022-11-01 23:24 UTC

**Comment by mengelbart** [comment] 2022-11-01 23:30
Oh, I overread that you're already using the feat/simplify-cgo-api branch so please ignore v0.0.1, v0.0.2 includes that branch on main.
https://github.com/mengelbart/rtp-over-quic/pull/3 includes this update in rtp-over-quic and should make it compile with the older glib.
